### ISSUE TITLE
Obsoletes RFC4941bis

### ISSUE THREAD

**Issue by otroan** [ietf-6man/4941bis#2]
https://github.com/ietf-6man/4941bis/blob/46b6007928f4635fe1d574035af037df1c1ae162/draft-ietf-6man-rfc4941bis.xml#L126

Needs to repeat that this obsoletes RFC4941 again here, and good to have a high level summary of what changed.

**Comment by fgont** [comment]
This has been addressed. Major changes are now discussed in Section "Significant Changes from RFC4941", while details have been moved to an appendix (to be removed by the RFC-Ed) -- at the end of the day, these details might be useful for us (6man) but not for the reader of the resulting RFC.
